### ISSUE TITLE
State via MQTT

### ISSUE THREAD

**Issue by zeljkoperic** [klausahrenberg/ThermostatBecaWifi#12]
It seems that i cant get thermostat state via mqtt. For example i have configured topic home/dnevna/thermostat. When publishing home/dnevna/thermostat/state/0 i dont get any response from thermostat. Am i doing something wrong maybe?

**Comment by coldfire84** [comment]
> When publishing home/dnevna/thermostat/state/0 i dont get any response

You need to use an inject node, with **string** payload of '**0**' with an MQTT out node that has topic set (in your case) to: **home/dnevna/thermostat/state**
