### ISSUE TITLE
What is hysteresis in this model?

### ISSUE THREAD

**Issue by itProfi** [klausahrenberg/ThermostatBecaWifi#2]
Dear friend! Can you say waht about hysteresis in this model? 1 or 0.5 degree?

**Comment by a-roz** [comment]
it's 0.5

**Comment by itProfi** [comment]
Mean, that is desured temp is 21 (for example) - on in 21, off in 21,5 and again on 21?

**Comment by a-roz** [comment]
If desired is 21,  it stops heat at 21, goes back to 20, and again start heat till 21

**Comment by itProfi** [comment]
ok, tnahks!
