### ISSUE TITLE
ESP8266 Module

### ISSUE THREAD

**Issue by tibo888** [klausahrenberg/ThermostatBecaWifi#21]
Hello, 
Great work, you r the best
But i would like to know what ESP8266 ESP-12 did you use ?

**Comment by TradeFace** [comment]
I used a ESP-12F. It fits the slot of the tuya-wifi module. Flashed this software on it; with a small modification for BHT-6000. 

I am not sure if that was really needed in hind sight. I couldn't get it to start in STA mode. The tuya app did find it at first install (with original firmware). I got the unit without a manual. So I figured there was no such function available. Later I found the manual for the BTH-6000 which shows how to put it in discovery mode. I didn't reflash it to check. 

In home-assistant I used the MQTT-HVAC (https://www.home-assistant.io/components/climate.mqtt/) to hook it up.
