### ISSUE TITLE
How can i turn on manualMode & Lock thermostat

### ISSUE THREAD

**Issue by rengaboy** [klausahrenberg/ThermostatBecaWifi#32]
Hello everyone.
I issued a problem, when i switch thermostat manually to scheduled mode, i can't switch it back with mqtt publish command. I also dont't understand, wnat topic i have to use with ecoMode, locked values. When i try to publish {\"manualMode\":true} to topic thermostat/hall/state, nothing happens.

**Comment by rengaboy** [comment]
i found mcu value already "55 aa 01 07 00 05 04 04 00 01 00", but when i try to publish it to mcucommand topic, also nothing happens

**Comment by ahmaddxb** [comment]
its thermostat/hall/manualMode and in the payload its true or false

This is an example of mine.
![image](https://user-images.githubusercontent.com/43728586/68085539-5e5ad180-fe5b-11e9-8c1f-0025a94d82a4.png)

**Comment by rengaboy** [comment]
Thank you, @ahmaddxb, i just found solution, after 10-time careful reading of readme.
