### ISSUE TITLE
Device supported by "normal" Tasmota Version?

### ISSUE THREAD

**Issue by helmar74** [klausahrenberg/ThermostatBecaWifi#36]
Hi,

the "normal" Tasmota Version also supports Templates.
Is it possible to use standard Tasmota version and configure the device with a template, or do I have to use this Firmware?

Thanks a lot

Helmar

**Comment by klausahrenberg** [comment]
Not possible with Tasmota and I have no plans to do that. Actual you have to use this firmware.
